version: '2'

services:
    reverseproxy:
        build:
            context: .
        ports:
            - 80:80
        restart: always

    portfolio:
        build:
            context: portfolio
        restart: always
        depends_on:
            - reverseproxy

    blog:
        image: wordpress
        volumes:
            - ./wordpress/wp_html:/var/www/html
        restart: always
        depends_on:
            - reverseproxy
            - wp_db

    wp_db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: examplepass

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: examplepass
            PMA_HOST: wp_db
        ports:
            - 9090:80
        depends_on:
            - wp_db
