version: '3.3'

services:
    reverseproxy:
        image: nginx:alpine
        volumes:
            - ./nginx-example.conf:/etc/nginx/nginx.conf
            - ./certs:/etc/nginx/certs/fluzadas.com
        ports:
            - 443:443
        restart: always

    portfolio:
        image: nginx:alpine
        restart: always
        volumes:
            - ./portfolio:/usr/share/nginx/html

    blog:
        image: wordpress
        volumes:
            - ./wordpress/wp_html:/var/www/html
        restart: always
        env_file:
            - .env
        environment:
            WORDPRESS_DB_HOST: wp_db:3306
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
            WORDPRESS_DB_NAME: wordpress
        depends_on:
            - wp_db

    wp_db:
        image: mysql:5.7
        volumes:
            - ./wp_db:/var/lib/mysql
        restart: always
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: ${WORDPRESS_DB_USER}
            MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        ports:
            - 3306:3306

volumes:
    wp_db: {}
