version: '3'

services:
    wordpress:
        image: wordpress
        volumes:
            - ~/wordpress/wp_html:/var/www/html
        depends_on:
            - wordpress_db
        ports:
            - 80:80
    wordpress_db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: examplepass
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - wordpress_db
        ports:
            - 8080:80
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: examplepass
            PMA_HOST: 172.24.0.2
